### ISSUE TITLE
misses of highbpm stacked streams

### ISSUE THREAD

**Issue by MiclySlGa** [ssCherry/hqosu-legacy#6]
It misses alot in stacked streams, for an example.
Call me it.(500 tortures) 5.49 stars, it misses alot of the stream and sometimes the spaced stream
The SAVEME is not helping on sliders to, like Triple Play where the saveme will pull back to the slider when going to the other slider

**Comment by Cammy16** [comment]
Finally someone who agrees with me: I normally play 7-8* no problem with the old hqosu but cherry's version can't hit stacks, spaced streams or normal streams. You really have to flick to EVERY circle for it to register. XD

**Comment by MiclySlGa** [comment]
i think before the update august  2019 was better than the update 17 days ago, i managed to really hit all of the streams  at Full metal dimension Freedom Dive then 7* one.

**Comment by MiclySlGa** [comment]
I Could tell that turning off "DoubleDelay" temporaly could help for the  stacked  streams

**Comment by ssCherry** [comment]
i don't changed in hq nothing just add some things in config and that's all also update on august was offset fix

**Comment by MiclySlGa** [comment]
Alright Then, keep  up  the good work ;3
